const WSPOLCZYNNIK_LEKARZ = 3;
const WSPOLCZYNNIK_ORDYNATOR = 4;
const WSPOLCZYNNIK_PIELEGNIARKA = 1;
const WSPOLCZYNNIK_PIELEGNIARKA_ODDZIALOWA = 2;

module.exports = {
    WSPOLCZYNNIK_LEKARZ,
    WSPOLCZYNNIK_ORDYNATOR,
    WSPOLCZYNNIK_PIELEGNIARKA,
    WSPOLCZYNNIK_PIELEGNIARKA_ODDZIALOWA
}
